### ISSUE TITLE
Cドライブ以外の場所に保管されているSRTを読み込むとエラーとなる

### ISSUE THREAD

**Issue by Yamamotoke2024** [ichiken-youtube/homophonic_checker#8]
srtファイルを「ここにD&D.bat」に他ドライブからDnDすると、
`D:\hogehoge\foobar.srt`
`python: can't open file 'D:\\hogehoge\homophonic_phrases.py': [Errno 2] No such file or directory`
となり正常に処理が進行しない。
Dドライブ以外の挙動は未調査

**Comment by EJFreaks** [comment]
起動用バッチファイルの作業ディレクトリ指定
`cd %~dp0`
に/dオプションが無いことが原因だと思われる(未検証)。
バッチファイルに任意のファイルをD&Dして起動した場合、デフォルトのワーキングディレクトリはバッチファイルの場所ではなく、D&Dしたファイルの場所になる。
したがって、他ドライブのファイルから起動された場合、ディレクトリをスクリプトの場所に移動する際にドライブを跨ぐ必要があるが、その際に/dオプションが必要になる

後日、検証ののち修正対応予定
